### ISSUE TITLE
Contrast applied to media embedded in the website

### ISSUE THREAD

**Issue by naveenjohnsonv** [galulex/deepdark#6]
You can test this simply by opening your own repo [main page](https://github.com/galulex/deepdark) and checking the images the toggle on and off. Not a dealbreaker for sure, but definitely significant enough that I have to toggle off the extension on YouTube and websites of the like.

**Comment by galulex** [comment]
@naveenjohnsonv Added another config specially for this case. I prefer media to be darken as well.
Please pull the latest changes if you are using unpacked extension. Or you can wait for chrome store update

**Comment by naveenjohnsonv** [comment]
Tried the config with Darken media toggled. Much better now, although not exactly the same as without dark mode toggled. Is it possible to toggle the darkening of images too? For example try the toggle opening [this image](https://user-images.githubusercontent.com/483482/200827812-17cc2981-c1ad-489c-a84e-ff24abf72a7e.png) in a new tab. Contrast is applied regardless of Darken media toggle.
