### ISSUE TITLE
Site-wise whitelists lost on browser close

### ISSUE THREAD

**Issue by naveenjohnsonv** [galulex/deepdark#7]
Didn't encounter this issue until a month ago or so. Previously if I disabled deepdark for a particular site it persisted across browser closes and open. But now if I close the browser and reopen I have to disable deepdark for those specific sites all over again and repeat the process every time.

**Comment by galulex** [comment]
@naveenjohnsonv Thanks for your bug report. Version 1.7 is in review. Should be published soon

**Comment by naveenjohnsonv** [comment]
Yes, it's fixed now! So I'll close this issue.
